### PR TITLE
threading calls to octokit

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@underscorgan can you have a look at this ?

**Comment by underscorgan** [comment]
@tphoney yeah, i'll try to review this in the next few days, been a bit swamped.

**Comment by tphoney** [comment]
@underscorgan i didnt mean to sound pushy

**Comment by underscorgan** [comment]
@tphoney you didn't, mostly I just wanted to let you know I saw this but hadn't had time, not that I hadn't seen it :)

**Comment by tphoney** [comment]
@underscorgan i know you are snowed under. any change you could have a quick look

**Comment by DavidS** [comment]
@underscorgan I noticed that I have the commit bit on this repo. Do you mind if I exercise it?

**Comment by underscorgan** [comment]
thanks for all your work @tphoney, and sorry for the delays!

**Pull request merged**
