### PR TITLE
remove windows supported modules

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by DavidS** [comment]
So this drops the windows modules on the floor, as there is no use of SUPPORTED_WINDOWS_MODULES_REGEX I can see. Perhaps add a filter option to expose this?

**Comment by tphoney** [comment]
This is part one of my 2 step plan .... mohahahahah
I am going to push this to the windows module team to gauge their support. They may not want to use these graphs/reports. 
If they want it, we can modify the scripts to use the windows regex as well.

**Comment by DavidS** [comment]
In the current state, the code has either too much (REs the code is not using) or not enough (options for the windows modules set).

**Comment by tphoney** [comment]
@DavidS removed the windows modules, these can be readded as their own regex. if needed.

**Pull request merged**
