### PR TITLE
npc: adds comments and labels to pr's

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@mhaskel can you have a look at this please

**Comment by underscorgan** [comment]
\o/

**Comment by igalic** [comment]
@tphoney wouldn't that rubycop.yml be a good fit for modulesync_configs?

**Comment by tphoney** [comment]
@igalic yes we need to use modulesync more, that is next on the list.

**Comment by igalic** [comment]
we (puppet-community) do too…

**Pull request merged**
